TRUNCATE TABLE TASK;

ALTER TABLE TASK ALTER COLUMN ID INT AUTO_INCREMENT(1);

INSERT INTO TASK(TITLE,DESCRIPTION,DEADLINE) VALUES('test1','test1','2024-01-31');
INSERT INTO TASK(TITLE,DESCRIPTION,DEADLINE) VALUES('test2','test2','2024-01-31');
INSERT INTO TASK(TITLE,DESCRIPTION,DEADLINE) VALUES('test3','test3','2024-01-31');
INSERT INTO TASK(TITLE,DESCRIPTION,DEADLINE) VALUES('test4','test4','2024-01-31');
