package jp.co.software.excite.taskmanager.infrastructure.entity;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.ID
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TITLE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.DESCRIPTION
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.STATUS
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.DEADLINE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.DEL_FLG
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    private Integer delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.ID
     *
     * @return the value of TASK.ID
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.ID
     *
     * @param id the value for TASK.ID
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TITLE
     *
     * @return the value of TASK.TITLE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TITLE
     *
     * @param title the value for TASK.TITLE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.DESCRIPTION
     *
     * @return the value of TASK.DESCRIPTION
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.DESCRIPTION
     *
     * @param description the value for TASK.DESCRIPTION
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.STATUS
     *
     * @return the value of TASK.STATUS
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.STATUS
     *
     * @param status the value for TASK.STATUS
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.DEADLINE
     *
     * @return the value of TASK.DEADLINE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.DEADLINE
     *
     * @param deadline the value for TASK.DEADLINE
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.DEL_FLG
     *
     * @return the value of TASK.DEL_FLG
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.DEL_FLG
     *
     * @param delFlg the value for TASK.DEL_FLG
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Task other = (Task) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()))
            && (this.getDelFlg() == null ? other.getDelFlg() == null : this.getDelFlg().equals(other.getDelFlg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Mon Jan 15 14:39:12 JST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        result = prime * result + ((getDelFlg() == null) ? 0 : getDelFlg().hashCode());
        return result;
    }
}