package com.excite.taskmanager.infrastructure.mapper;

import com.excite.taskmanager.infrastructure.entity.Task;
import com.excite.taskmanager.infrastructure.entity.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int insert(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int insertSelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int updateByExampleSelective(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int updateByExample(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int updateByPrimaryKeySelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Tue Jan 16 13:36:48 JST 2024
     */
    int updateByPrimaryKey(Task row);
}